services:
  - type: web
    name: sonemote-app
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1
      pip install -r requirements.txt
    startCommand: python app.py
